#!/usr/bin/env bash
# configure a ufw firewall to block all incomming traffic
#  except for TCP port 33, 80 and 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo  ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
